### ISSUE TITLE
Could not find class: java/lang/StrictMath

### ISSUE THREAD

**Issue by texadactyl** [platypusguy/jacobin#19]
[try_math.java.zip](https://github.com/platypusguy/jacobin/files/10327081/try_math.java.zip)

java try_math
===== Begin
===== End

jacobin try_math.class
===== Begin
Could not find class: java/lang/StrictMath

**Comment by platypusguy** [comment]
I think that worrying about whether to use the classlist to load a basic set of classes at startup is a bit of a red herring. There will always be some basic list that we load, whether it's classlist or something else. What we need here, IMHO, is to be able to fill in the remaining Java classes that are needed for execution from the jmod files quickly. I've opened JACOBIN-207 in the tracker for that issue.

**Comment by texadactyl** [comment]
@platypusguy 
* Simply reporting an apparent error in the jacobin classloader. Not sure what it is at the moment. Will look at the source code when I have some free time if it is not addressed sooner.  Sorry, hip-deep in something else at the moment.
* Not sure what the JACOBIN tracker is.  I thought that this github project is where you are tracking all issues?

**Comment by platypusguy** [comment]
The error is because you need a class from the JDK distribution that was not preloaded among the 1400 classes we preload when Jacobin starts up. At the moment, we don't have a way to load additional JDK classes, which is the basis of my comment that we need to write that code. (It was omitted because the early POC classes had all the classes they needed in the preload classes. With this program, that's no longer the case. Hence, the error message.)

I'll DM you directly about access to the task list/defect tracker on YouTrack. One of the things we do with Jacobin is a kind of traceability in which every change we make in Jacobin is tied to an item in the tracker. In the[ github source directory](https://github.com/platypusguy/jacobin/tree/main/src), you'll see that every change is associated with a JACOBIN-### style entry

**Comment by texadactyl** [comment]
"need a class from the JDK distribution that was not preloaded" Ok, got it.

**Comment by texadactyl** [comment]
To me, Go is like Julia without the installation-design hoops one has to jump through because of the JIT nature.  Simplistic comparison, I'll admit.  Julia is on a track to become as popular as Python with the science communities.

**Comment by texadactyl** [comment]
Tracked in https://jacobin.myjetbrains.com/youtrack/issue/JACOBIN-207
