### ISSUE TITLE
Is the plan to create a new JCL?

### ISSUE THREAD

**Issue by Thihup** [platypusguy/jacobin#5]
One of the key components of a Java SE implementation is the Class Library.
Currently, I only know that OpenJDK has a complete implementation of the Class Library.
It is a little coupled to the Hotspot VM, however, other JVMs, like OpenJ9 can use it.

So my question is: Is one of the goals of this project reimplement the whole Java Class Library
(like the `java.lang.Object`/`java.util.HashMap`, ...) or use the same as OpenJDK?

There are some other implementations of some components that wouldn't be required to
be implemented, like using the ECJ for the compiler and Kodda for a replacement of Javadoc.

(The license of  the JCL is GPL2, so it may play some role in the decision)

**Comment by platypusguy** [comment]
Not at present, no. That would truly be a massive undertaking! When all is said and done, Jacobin should be able to run the Java class libraries without reimplementing them. Nonetheless, some classes will need to be rewritten in go: 1) for performance reasons, 2) because they're OS-specific, 3) because they're presently not available as bytecode. 

Jacobin has the capability now to run go methods. It's still in prototype stage, but, for example, it allowed us earlier this week to successfully run our first Java class by using a go-native version of System.out.println(). Detailed implementation notes for the operations of this prototype system are shown in [javaPrintStream.go](https://github.com/platypusguy/jacobin/blob/main/src/exec/javaPrintStream.go)

**Comment by texadactyl** [comment]
Whenever I see the acronym "JCL", I always think fondly of my z/OS days.

Joyieux << Merci Donnant >> !

**Comment by platypusguy** [comment]
I don't miss IBM JCL at all. There's no "fondly" in it for me.
