### ISSUE TITLE
jvm.pop() index out of range

### ISSUE THREAD

**Issue by Surendrajat** [platypusguy/jacobin#67]
Trying to run [uber-apk-signer](https://github.com/patrickfav/uber-apk-signer/releases/tag/v1.2.1) with jacobin results in this panic:
```
$ ./jacobin -jar uber-apk-signer-1.2.1.jar
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
jacobin/jvm.pop(0x0?)
	/Users/s/jacobin/src/jvm/run.go:2321 +0x6d8
jacobin/jvm.createAndInitNewFrame({0x140041930e0, 0x21}, {0x14004cbac10, 0xb}, {0x140041d4a80, 0x3f}, 0x1400014f868, 0x0, 0x330?)
	/Users/s/jacobin/src/jvm/run.go:2611 +0xac4
jacobin/jvm.runFrame(0x14004cc5a40)
	/Users/s/jacobin/src/jvm/run.go:1834 +0x7064
jacobin/jvm.runThread(0x102984800)
	/Users/s/jacobin/src/jvm/run.go:92 +0x3c
jacobin/jvm.StartExec({0x140041930e0, 0x21}, 0x102984d60)
	/Users/s/jacobin/src/jvm/run.go:82 +0x658
jacobin/jvm.JVMrun()
	/Users/s/jacobin/src/jvm/jvmStart.go:94 +0x4cc
main.main()
	/Users/s/jacobin/src/main.go:12 +0x1c
```

I tried to avoid it with following patch:
```diff
diff --git a/src/jvm/run.go b/src/jvm/run.go
index ec812cc..0c66485 100644
--- a/src/jvm/run.go
+++ b/src/jvm/run.go
@@ -2318,6 +2318,9 @@ func emitTraceData(f *frames.Frame) string {

 // pop from the operand stack. TODO: need to put in checks for invalid pops
 func pop(f *frames.Frame) interface{} {
+   if f.TOS < 0 {
+       return nil
+   }
    value := f.OpStack[f.TOS]

    // we show trace info of the TOS *before* we change its value--
```

But then it throws this error:
```
$ ./jacobin -jar uber-apk-signer-1.2.1.jar
LoadClassFromFile: os.ReadFile(at/favre/tools/apksigner/ui/CLIParser.class) failed
LoadClassFromNameOnly: LoadClassFromFile at/favre/tools/apksigner/ui/CLIParser failed
open at/favre/tools/apksigner/ui/CLIParser.class: no such file or directory
FetchMethodAndCP: LoadClassFromNameOnly for at/favre/tools/apksigner/ui/CLIParser failed: open at/favre/tools/apksigner/ui/CLIParser.class: no such file or directory
open at/favre/tools/apksigner/ui/CLIParser.class: no such file or directory
```

**Comment by platypusguy** [comment]
Thanks for this. As mentioned in the release notes, Jacobin is not yet ready for testing outside the dev team. We're hoping in the next year, to offer a release for which we can solicit kind users such as you to try out and report their experience.

I appreciate the suggested code edit, but all that does is transfer the error to somewhere else in the program. The solution is to find the root cause that led to the stack underflow. Most likely, it's some thing we're working on at present or will be working on soon. 
 
I'll close this issue for the time being and circle back to it when we're ready to do public testing. I hope/trust that by then the jar file you used will run flawlessly. 
 
Thanks again!

**Comment by Surendrajat** [comment]
Thanks for taking the time to reply.
> As mentioned in the release notes, Jacobin is not yet ready for testing outside the dev team

I missed that. If possible, could you please add a little note in README instead?
Anyway looking forward to giving it a try again.

**Comment by platypusguy** [comment]
Excellent idea! Will do.
