### ISSUE TITLE
when will jacobin ve first released in plan

### ISSUE THREAD

**Issue by Nyx2022** [platypusguy/jacobin#76]
i read the blogs,and found the jacobin is brilliant,but it is not released for now ,so i wanna know when is it will be release in plan?i wanna test it and enjoy it ,thank you

**Comment by platypusguy** [comment]
Nyx, thanks for your inquiry. We're currently working on the JVM exception mechanism and proper handling of abstract classes. We also need to finish up work on native methods (the methods that the JDK implements as .dll files on Windows, and .lib/.so files on Linux, etc.) We expect that will take us to the 30-month mark (so, February 2024). After that, we expect to spend a few months cleaning up the user experience, before doing some beta testing. We welcome your participation in that testing. To be kept up-to-date on this schedule, follow us on Twitter/X at @jacobin_jvm or follow the blog at https://binstock.blogspot.com/. 

If you'd like to test it before then, post a comment to the blog with your contact info. This will not appear in public b/c I moderate all comments. And I'll put you on a list of early testers, so that you can be involved in that alpha testing. Again, thank you for your interest.

**Comment by Nyx2022** [comment]
> Nyx, thanks for your inquiry. We're currently working on the JVM exception mechanism and proper handling of abstract classes. We also need to finish up work on native methods (the methods that the JDK implements as .dll files on Windows, and .lib/.so files on Linux, etc.) We expect that will take us to the 30-month mark (so, February 2024). After that, we expect to spend a few months cleaning up the user experience, before doing some beta testing. We welcome your participation in that testing. To be kept up-to-date on this schedule, follow us on Twitter/X at @jacobin_jvm or follow the blog at https://binstock.blogspot.com/.
> 
> If you'd like to test it before then, post a comment to the blog with your contact info. This will not appear in public b/c I 


thank you for your reply, i beleieve jacobin will be a very very Successful project，i can wait to the first release be published and test it after a few months later, best wishes to your team members!
